[build]
  # где искать package.json и запускать команды
  base    = "frontend"
  # куда класть собранные файлы (relative to base)
  publish = "build"
  # команда сборки React-приложения
  command = "yarn build"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
